# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .

  database:
    image: mariadb:10.4
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - default_time_zone=Europe/Paris
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  database: ~